
# hyperledger
@url = http://188.116.40.21:3000/api
###

# eos
# @url = http://188.116.40.21:18888


# hyperleder local
# GET http://localhost:3000/api

# asset

###
GET {{url}}/EternalTrustsAsset/

###
POST {{url}}/EternalTrustsAsset
content-type: application/json

{
  "$class": "com.eternaltrusts.privatenetwork.EternalTrustsAsset",
  "assetId": "asset1",
  "owner": "com.eternaltrusts.privatenetwork.EternalTrustsParticipant#id1",
  "value": "111"
}


###
@asset_id = asset2
GET {{url}}/EternalTrustsAsset/{{asset_id}}

###
HEAD {{url}}/EternalTrustsAsset/{{asset_id}}

###
PUT {{url}}/EternalTrustsAsset/{id}

###
DELETE {{url}}/EternalTrustsAsset/{id}

# participant

###
GET {{url}}/EternalTrustsParticipant

###
POST {{url}}/EternalTrustsParticipant
content-type: application/json

{
  "$class": "com.eternaltrusts.privatenetwork.EternalTrustsParticipant",
  "participantId": "id1",
  "firstName": "firstName1",
  "lastName": "lastName1"
}

###
GET {{url}}/EternalTrustsParticipant/{id}

###
HEAD {{url}}/EternalTrustsParticipant/{id}

###
PUT {{url}}/EternalTrustsParticipant/{id}

###
DELETE {{url}}/EternalTrustsParticipant/{id}

# transaction

###
GET {{url}}/EternalTrustsTransaction

###
POST {{url}}/EternalTrustsTransaction
content-type: application/json

{
  "$class": "com.eternaltrusts.privatenetwork.EternalTrustsTransaction",
  "asset": "com.eternaltrusts.privatenetwork.EternalTrustsAsset#asset1",
  "newValue": "444"
}

###
GET {{url}}/EternalTrustsTransaction/{id}


###

GET http://188.116.40.21:3000/api/EternalTrustsAsset